secret_key_base: 1zJfc47j3KeipIgqbkGGJNcZ2-Xh3pZwmE_Yd6xqKf4
port: 3000
name: pet-tracker

logging:
  severity: debug
  colorize: true
  filter:
    - password
    - confirm_password
  context:
    - request
    - session
    - headers
    - cookies
    - params

host: 0.0.0.0
port_reuse: true
process_count: 1
# ssl_key_file:
# ssl_cert_file:
redis_url: "redis://localhost:6379"
database_url: postgres://ruifreitas:@localhost:5432/pet_tracker_development

session:
  key: amber.session
  store: signed_cookie
  expires: 0

smtp:
  enabled: false

secrets:
  description: Store your development secrets credentials and settings here.

